apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ku50xaqbc-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ku50xaqbc-nodejs 
  name: ku50xaqbc-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ku50xaqbc-nodejs 
